spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: "org.hibernate.dialect.H2Dialect"
        "[default_batch_fetch_size]": 100
        "[use_scrollable_resultset]": true
    hibernate:
      naming:
        physical-strategy: "org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl"
      ddl-auto: "create"
  datasource:
    url: "jdbc:h2:file:./crm;DB_CLOSE_DELAY=-1"
    username: "sa"
    password: ""
    driver-class-name: "org.h2.Driver"

elide:
  modelPackage: "com.empyrean.elide.crm.models"
  pageSize: 1000
  maxPageSize: 10000
  json-api:
    path: /api/v1
    enabled: true
  graphql:
    path: /graphql/api/v1
    enabled: true
  swagger:
    path: /doc
    enabled: true
    name: "Elide CRM"
    version: "1.0"

logging:
  file:
    path: /tmp

security:
  origin: "*"
